name: note_takey
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  auto_route: ^2.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_staggered_grid_view: ^0.4.0
  freezed_annotation: ^0.14.3
  hooks_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/hooks_riverpod
  intl: ^0.17.0
  oauth2: ^2.0.0
  provider: ^5.0.0
  webview_flutter: ^2.0.12

dev_dependencies:
  auto_route_generator: ^2.3.0
  build_runner: ^2.1.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  lint: ^1.7.2

dependency_overrides:
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/flutter_riverpod
  riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/riverpod

flutter:
  uses-material-design: true
